### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mikeygio10** [AndreasHGK/MultiPort#1]
i added a port but when i try to join with it does not work

**Comment by mikeygio10** [comment]
# Add as many ports as you like. do it like the example shown without the hashtag.

ports:
  - 19134

**Comment by mikeygio10** [comment]
thats the cofig

**Comment by andreashgk** [comment]
Should work. Any errors?

**Comment by mikeygio10** [comment]
no

**Comment by mikeygio10** [comment]
does not show up my ign in console

**Comment by andreashgk** [comment]
Is the port forwarded?

**Comment by andreashgk** [comment]
If you're renting from a host, they might not have given you access to use that port

**Comment by mikeygio10** [comment]
o that could be it
