### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Wertzui123** [AndreasHGK/MultiPort#2]
I can't join to my server with another port than the default...

**Comment by andreashgk** [comment]
Is the port forwarded?
Does your host allow you to use this port?

**Comment by Wertzui123** [comment]
I don't know. I use minehub.de

**Comment by andreashgk** [comment]
Yes, they probably only allow you to use 1 port. Ask them to open a second one for you. Duplicate of #1

**Comment by Wertzui123** [comment]
Okey, sorry
