### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by provsalt** [AndreasHGK/MultiPort#3]
I place 19130-19140 ports
My host is microsoft azure
and it allows me to open port like 19132
i opened all ports but it didnt worked
anyways to fix this?

**Comment by andreashgk** [comment]
Did you forward the ports?

**Comment by provsalt** [comment]
yes i did and all ports open

**Comment by provsalt** [comment]
i placed a * to open all ports but 19132 deafult works fine

**Comment by andreashgk** [comment]
Where did you place a *?

**Comment by provsalt** [comment]
https://ibb.co/HqhbmG6

**Comment by andreashgk** [comment]
Try putting the ports in manually

**Comment by provsalt** [comment]
heres a pic of my networking settings

**Comment by provsalt** [comment]
what do you mean?

**Comment by provsalt** [comment]
got it working
idk why but the config file added a # there
and making me confused it now works.
